import esbuild from "esbuild";
import process from "process";
import builtins from "builtin-modules";

const production = process.argv[2] === "production";

const banner = `/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
Source code is in the src/ directory.
*/`;

// Node core modules are available at runtime in Obsidian's Electron renderer
// (used by the AWS credential file reader). Externalize both bare and "node:"
// scheme names so they resolve at runtime rather than being bundled.
const nodeExternals = [...builtins, ...builtins.map((m) => `node:${m}`)];

const context = await esbuild.context({
  banner: { js: banner },
  entryPoints: ["src/main.ts"],
  bundle: true,
  // Browser platform: required for onnxruntime-web (Whisper WASM) to use its
  // browser code paths instead of node worker_threads/fs, which crash inside
  // the Electron renderer. We dropped the AWS SDK (which needed node platform)
  // in favour of a small Web Crypto SigV4 signer, so browser platform is safe.
  platform: "browser",
  external: [
    "obsidian",
    "electron",
    "@codemirror/autocomplete",
    "@codemirror/collab",
    "@codemirror/commands",
    "@codemirror/language",
    "@codemirror/lint",
    "@codemirror/search",
    "@codemirror/state",
    "@codemirror/view",
    "@lezer/common",
    "@lezer/highlight",
    "@lezer/lr",
    // transformers.js optionally pulls in native deps not used for audio.
    "sharp",
    ...nodeExternals,
  ],
  // Obsidian's Electron renderer is detected as "node" by transformers.js, so
  // its backend does `import 'onnxruntime-node'`. We don't ship native
  // binaries — alias it to the WASM `onnxruntime-web` runtime so the import
  // resolves and is bundled (must NOT also be in `external`, or it becomes a
  // failing runtime require).
  alias: {
    "onnxruntime-node": "onnxruntime-web",
  },
  format: "cjs",
  target: "es2020",
  logLevel: "info",
  sourcemap: production ? false : "inline",
  treeShaking: true,
  outfile: "main.js",
  define: {
    "process.env.NODE_ENV": production ? '"production"' : '"development"',
    // transformers.js computes a "local" path from `import.meta.url`, which is
    // undefined in a CJS bundle and crashes `fileURLToPath`. Define it to a
    // dummy file URL so that call succeeds; we force remote models at runtime
    // (env.allowLocalModels = false), so the computed local paths are unused.
    "import.meta.url": '"file:///obsidian-plugin/main.js"',
  },
});

if (production) {
  await context.rebuild();
  process.exit(0);
} else {
  await context.watch();
}
