import esbuild from "esbuild";
import process from "process";
import builtins from "builtin-modules";

const production = process.argv[2] === "production";

const banner = `/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
Source code is in the src/ directory.
*/`;

// Node core modules are available at runtime (desktop-only Electron plugin).
// Externalize both the bare names and the "node:" scheme so the AWS SDK's
// credential providers (which import "node:fs", "node:child_process", etc.)
// resolve at runtime instead of being bundled.
const nodeExternals = [...builtins, ...builtins.map((m) => `node:${m}`)];

const context = await esbuild.context({
  banner: { js: banner },
  entryPoints: ["src/main.ts"],
  bundle: true,
  external: [
    "obsidian",
    "electron",
    "@codemirror/autocomplete",
    "@codemirror/collab",
    "@codemirror/commands",
    "@codemirror/language",
    "@codemirror/lint",
    "@codemirror/search",
    "@codemirror/state",
    "@codemirror/view",
    "@lezer/common",
    "@lezer/highlight",
    "@lezer/lr",
    // transformers.js optionally pulls in `sharp` (image processing); not used
    // for audio, so exclude it.
    "sharp",
    ...nodeExternals,
  ],
  // Obsidian's Electron renderer reports as a "node" environment, so
  // transformers.js tries to import the native `onnxruntime-node`. We don't
  // bundle native binaries — alias it to the WASM `onnxruntime-web` runtime so
  // the import resolves and Whisper runs in WASM.
  alias: {
    "onnxruntime-node": "onnxruntime-web",
  },
  format: "cjs",
  platform: "node",
  target: "es2020",
  logLevel: "info",
  sourcemap: production ? false : "inline",
  treeShaking: true,
  outfile: "main.js",
  define: { "process.env.NODE_ENV": production ? '"production"' : '"development"' },
});

if (production) {
  await context.rebuild();
  process.exit(0);
} else {
  await context.watch();
}
